// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function ApplyProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1891702200, id);
}

export function CreateProfile(name: string): $CancellablePromise<domain$0.EQProfile | null> {
    return $Call.ByID(4064694210, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3089149179, id);
}

export function GetActiveProfile(): $CancellablePromise<domain$0.EQProfile | null> {
    return $Call.ByID(3246786438).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAllProfiles(): $CancellablePromise<(domain$0.EQProfile | null)[]> {
    return $Call.ByID(2567533384).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(342202204, enabled);
}

export function UpdateBand(profileID: string, bandIndex: number, gain: number): $CancellablePromise<void> {
    return $Call.ByID(1712355375, profileID, bandIndex, gain);
}

// Private type creation functions
const $$createType0 = domain$0.EQProfile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
