// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetPlatform(): $CancellablePromise<string> {
    return $Call.ByID(2146017041);
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(841082507, name);
}
