// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function AddFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(394401443, path);
}

export function DeleteTrack(trackID: string): $CancellablePromise<void> {
    return $Call.ByID(2485294230, trackID);
}

export function GetAlbumByID(id: string): $CancellablePromise<domain$0.AlbumDTO | null> {
    return $Call.ByID(3483474319, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAlbumColors(id: string): $CancellablePromise<domain$0.ThemeColors | null> {
    return $Call.ByID(1796143855, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAlbumsByArtistID(artistID: string): $CancellablePromise<(domain$0.AlbumDTO | null)[]> {
    return $Call.ByID(1262692927, artistID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAllAlbums(): $CancellablePromise<(domain$0.AlbumDTO | null)[]> {
    return $Call.ByID(3744286339).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAllArtists(): $CancellablePromise<(domain$0.Artist | null)[]> {
    return $Call.ByID(452267397).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetAllComposers(): $CancellablePromise<(domain$0.Composer | null)[]> {
    return $Call.ByID(2962536066).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetAllGenres(): $CancellablePromise<(domain$0.Genre | null)[]> {
    return $Call.ByID(1925972487).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetAllTracks(): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(359687051).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetArtistByID(id: string): $CancellablePromise<domain$0.Artist | null> {
    return $Call.ByID(1440109499, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetComposerByID(id: string): $CancellablePromise<domain$0.Composer | null> {
    return $Call.ByID(571413398, id).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetFavoriteTracks(): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(1643839000).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetGenreByID(id: string): $CancellablePromise<domain$0.Genre | null> {
    return $Call.ByID(2618260199, id).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetRecentlyAddedAlbums(limit: number): $CancellablePromise<(domain$0.AlbumDTO | null)[]> {
    return $Call.ByID(1096166738, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSyncStatus(): $CancellablePromise<domain$0.SyncProgress | null> {
    return $Call.ByID(1653948325).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetTracksByAlbumID(albumID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(4163104693, albumID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetTracksByArtistID(artistID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(216842599, artistID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetTracksByComposerID(composerID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(1105504066, composerID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetTracksByGenreID(genreID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(2932375161, genreID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetWatchedFolders(): $CancellablePromise<(domain$0.WatchedFolder | null)[]> {
    return $Call.ByID(3207537371).then(($result: any) => {
        return $$createType21($result);
    });
}

export function RemoveFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(3590204360, id);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(2219288800);
}

export function SyncAll(): $CancellablePromise<void> {
    return $Call.ByID(3300374490);
}

export function ToggleFavorite(trackID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3821657700, trackID);
}

export function UpdateTrackMetadata(trackID: string, update: domain$0.MetadataUpdate): $CancellablePromise<void> {
    return $Call.ByID(3547274065, trackID, update);
}

// Private type creation functions
const $$createType0 = domain$0.AlbumDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = domain$0.ThemeColors.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = domain$0.Artist.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = domain$0.Composer.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = domain$0.Genre.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = domain$0.TrackDTO.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = domain$0.SyncProgress.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = domain$0.WatchedFolder.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $Create.Array($$createType20);
