// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function DeleteLyrics(trackID: string): $CancellablePromise<void> {
    return $Call.ByID(433055224, trackID);
}

/**
 * FetchLyrics fetches lyrics from lrclib.net for the given track and returns the result.
 */
export function FetchLyrics(trackID: string, track: domain$0.TrackDTO | null): $CancellablePromise<domain$0.Lyric | null> {
    return $Call.ByID(1354700981, trackID, track).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLyrics(trackID: string): $CancellablePromise<domain$0.Lyric | null> {
    return $Call.ByID(3051041221, trackID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveLyrics(trackID: string, content: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(4037936082, trackID, content, source);
}

// Private type creation functions
const $$createType0 = domain$0.Lyric.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
