// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService is the Wails binding for playback controls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function GetQueue(): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(3092492609).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetStatus(): $CancellablePromise<domain$0.PlayerStatus> {
    return $Call.ByID(2225965096).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Next(): $CancellablePromise<void> {
    return $Call.ByID(777386567);
}

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(1548241692);
}

export function Play(): $CancellablePromise<void> {
    return $Call.ByID(447319412);
}

export function PlayNext(track: domain$0.TrackDTO | null): $CancellablePromise<void> {
    return $Call.ByID(2410423757, track);
}

export function PlayNextTracks(tracks: (domain$0.TrackDTO | null)[]): $CancellablePromise<void> {
    return $Call.ByID(948008917, tracks);
}

export function PlayTracks(tracks: (domain$0.TrackDTO | null)[], startIndex: number): $CancellablePromise<void> {
    return $Call.ByID(831343208, tracks, startIndex);
}

export function Previous(): $CancellablePromise<void> {
    return $Call.ByID(4076836127);
}

export function Seek(position: number): $CancellablePromise<void> {
    return $Call.ByID(3998650994, position);
}

export function SetMuted(muted: boolean): $CancellablePromise<void> {
    return $Call.ByID(2392530493, muted);
}

export function SetRepeatMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(986951570, mode);
}

export function SetShuffle(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(890663075, enabled);
}

export function SetVolume(volume: number): $CancellablePromise<void> {
    return $Call.ByID(1067437308, volume);
}

export function ShuffleTracks(tracks: (domain$0.TrackDTO | null)[]): $CancellablePromise<void> {
    return $Call.ByID(3550810531, tracks);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2479813202);
}

// Private type creation functions
const $$createType0 = domain$0.TrackDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.PlayerStatus.createFrom;
