// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function AddTrackToPlaylist(playlistID: string, trackID: string): $CancellablePromise<void> {
    return $Call.ByID(3952904816, playlistID, trackID);
}

export function CreatePlaylist(name: string, description: string): $CancellablePromise<domain$0.Playlist | null> {
    return $Call.ByID(783157459, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeletePlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(1239427820, id);
}

export function GetAllPlaylists(): $CancellablePromise<(domain$0.Playlist | null)[]> {
    return $Call.ByID(3723506981).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPlaylistByID(id: string): $CancellablePromise<domain$0.Playlist | null> {
    return $Call.ByID(4053493933, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPlaylistColors(id: string): $CancellablePromise<domain$0.ThemeColors | null> {
    return $Call.ByID(2874653605, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetPlaylistTracks(playlistID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(1937479585, playlistID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RemovePlaylistArtwork(id: string): $CancellablePromise<void> {
    return $Call.ByID(3995918165, id);
}

export function RemoveTrackFromPlaylist(playlistID: string, trackID: string): $CancellablePromise<void> {
    return $Call.ByID(1450009730, playlistID, trackID);
}

export function SelectAndSetPlaylistArtwork(id: string): $CancellablePromise<string> {
    return $Call.ByID(140882432, id);
}

export function UpdatePlaylist(id: string, name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(1309793242, id, name, description);
}

// Private type creation functions
const $$createType0 = domain$0.Playlist.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.ThemeColors.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = domain$0.TrackDTO.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
