// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function GetSettings(): $CancellablePromise<domain$0.AppSettings | null> {
    return $Call.ByID(3355188131).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveSettings(settings: domain$0.AppSettings | null): $CancellablePromise<void> {
    return $Call.ByID(3211069562, settings);
}

// Private type creation functions
const $$createType0 = domain$0.AppSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
