// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService manages secondary windows (mini player).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function CloseMiniPlayer(): $CancellablePromise<void> {
    return $Call.ByID(1249666923);
}

export function OpenMiniPlayer(): $CancellablePromise<void> {
    return $Call.ByID(3080692785);
}

export function SetMainWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(908899340, w);
}

export function SetMiniWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3439326910, w);
}

export function ToggleMiniPlayer(): $CancellablePromise<void> {
    return $Call.ByID(2631702209);
}
