// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function AddFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2789466282, path);
}

export function GetAlbumByID(id: string): $CancellablePromise<domain$0.AlbumDTO | null> {
    return $Call.ByID(3337931472, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAlbumsByArtistID(artistID: string): $CancellablePromise<(domain$0.AlbumDTO | null)[]> {
    return $Call.ByID(1076010318, artistID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAllAlbums(): $CancellablePromise<(domain$0.AlbumDTO | null)[]> {
    return $Call.ByID(2644391788).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAllArtists(): $CancellablePromise<(domain$0.Artist | null)[]> {
    return $Call.ByID(2362731224).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetAllComposers(): $CancellablePromise<(domain$0.Composer | null)[]> {
    return $Call.ByID(461477571).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetAllGenres(): $CancellablePromise<(domain$0.Genre | null)[]> {
    return $Call.ByID(243062740).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetAllTracks(): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(310167268).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetArtistByID(id: string): $CancellablePromise<domain$0.Artist | null> {
    return $Call.ByID(3230361870, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetComposerByID(id: string): $CancellablePromise<domain$0.Composer | null> {
    return $Call.ByID(325560727, id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetGenreByID(id: string): $CancellablePromise<domain$0.Genre | null> {
    return $Call.ByID(222074596, id).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetRecentlyAddedAlbums(limit: number): $CancellablePromise<(domain$0.AlbumDTO | null)[]> {
    return $Call.ByID(1918903465, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetSyncStatus(): $CancellablePromise<domain$0.SyncProgress | null> {
    return $Call.ByID(618214912).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetTracksByAlbumID(albumID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(1363720402, albumID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetTracksByArtistID(artistID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(3110984398, artistID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetTracksByComposerID(composerID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(1239947303, composerID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetTracksByGenreID(genreID: string): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(3265648650, genreID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetWatchedFolders(): $CancellablePromise<(domain$0.WatchedFolder | null)[]> {
    return $Call.ByID(265880194).then(($result: any) => {
        return $$createType19($result);
    });
}

export function RemoveFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(1021292127, id);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1031094819);
}

export function SyncAll(): $CancellablePromise<void> {
    return $Call.ByID(3735902819);
}

// Private type creation functions
const $$createType0 = domain$0.AlbumDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.Artist.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = domain$0.Composer.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = domain$0.Genre.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = domain$0.TrackDTO.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = domain$0.SyncProgress.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = domain$0.WatchedFolder.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Array($$createType18);
