// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function AddFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2789466282, path);
}

export function GetWatchedFolders(): $CancellablePromise<(domain$0.WatchedFolder | null)[]> {
    return $Call.ByID(265880194).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RemoveFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(1021292127, id);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1031094819);
}

// Private type creation functions
const $$createType0 = domain$0.WatchedFolder.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
