// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export class SearchResultSet {
    "tracks": (domain$0.TrackDTO | null)[];
    "albums": (domain$0.AlbumDTO | null)[];
    "artists": (domain$0.Artist | null)[];

    /** Creates a new SearchResultSet instance. */
    constructor($$source: Partial<SearchResultSet> = {}) {
        if (!("tracks" in $$source)) {
            this["tracks"] = [];
        }
        if (!("albums" in $$source)) {
            this["albums"] = [];
        }
        if (!("artists" in $$source)) {
            this["artists"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResultSet instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResultSet {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField0_0($$parsedSource["tracks"]);
        }
        if ("albums" in $$parsedSource) {
            $$parsedSource["albums"] = $$createField1_0($$parsedSource["albums"]);
        }
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField2_0($$parsedSource["artists"]);
        }
        return new SearchResultSet($$parsedSource as Partial<SearchResultSet>);
    }
}

// Private type creation functions
const $$createType0 = domain$0.TrackDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.AlbumDTO.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = domain$0.Artist.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
