// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService is the Wails binding for playback controls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

export function GetQueue(): $CancellablePromise<(domain$0.TrackDTO | null)[]> {
    return $Call.ByID(533657436).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetStatus(): $CancellablePromise<domain$0.PlayerStatus> {
    return $Call.ByID(1457539731).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Next(): $CancellablePromise<void> {
    return $Call.ByID(4192570598);
}

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(3359510743);
}

export function Play(): $CancellablePromise<void> {
    return $Call.ByID(2740923477);
}

export function PlayTracks(tracks: (domain$0.TrackDTO | null)[], startIndex: number): $CancellablePromise<void> {
    return $Call.ByID(2021690605, tracks, startIndex);
}

export function Previous(): $CancellablePromise<void> {
    return $Call.ByID(275807114);
}

export function Seek(position: number): $CancellablePromise<void> {
    return $Call.ByID(201227107, position);
}

export function SetMuted(muted: boolean): $CancellablePromise<void> {
    return $Call.ByID(821275176, muted);
}

export function SetRepeatMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3682635369, mode);
}

export function SetShuffle(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3455733206, enabled);
}

export function SetVolume(volume: number): $CancellablePromise<void> {
    return $Call.ByID(3604988375, volume);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3235842495);
}

// Private type creation functions
const $$createType0 = domain$0.TrackDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.PlayerStatus.createFrom;
