// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * WatchedFolder represents a directory being watched for music files
 */
export class WatchedFolder {
    "id": string;
    "path": string;
    "created_at": time$0.Time;

    /** Creates a new WatchedFolder instance. */
    constructor($$source: Partial<WatchedFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchedFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchedFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchedFolder($$parsedSource as Partial<WatchedFolder>);
    }
}
