// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Album represents a music album
 */
export class Album {
    "id": string;
    "title": string;
    "sort_title": string;
    "normalization_key": string;
    "year": number;
    "copyright": string;
    "artwork_key": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Album instance. */
    constructor($$source: Partial<Album> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sort_title" in $$source)) {
            this["sort_title"] = "";
        }
        if (!("normalization_key" in $$source)) {
            this["normalization_key"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("copyright" in $$source)) {
            this["copyright"] = "";
        }
        if (!("artwork_key" in $$source)) {
            this["artwork_key"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     */
    static createFrom($$source: any = {}): Album {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album($$parsedSource as Partial<Album>);
    }
}

/**
 * AlbumDTO represents an album with its related entities populated for the frontend
 */
export class AlbumDTO {
    "id": string;
    "title": string;
    "sort_title": string;
    "normalization_key": string;
    "year": number;
    "copyright": string;
    "artwork_key": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "artists"?: (Artist | null)[];

    /** Creates a new AlbumDTO instance. */
    constructor($$source: Partial<AlbumDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sort_title" in $$source)) {
            this["sort_title"] = "";
        }
        if (!("normalization_key" in $$source)) {
            this["normalization_key"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("copyright" in $$source)) {
            this["copyright"] = "";
        }
        if (!("artwork_key" in $$source)) {
            this["artwork_key"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumDTO {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField9_0($$parsedSource["artists"]);
        }
        return new AlbumDTO($$parsedSource as Partial<AlbumDTO>);
    }
}

/**
 * AppSettings holds general application settings
 */
export class AppSettings {
    "language": string;

    /**
     * "system", "light", "dark"
     */
    "theme": string;
    "start_at_login": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("start_at_login" in $$source)) {
            this["start_at_login"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * Artist represents a music artist
 */
export class Artist {
    "id": string;
    "name": string;
    "sort_name": string;
    "normalization_key": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Artist instance. */
    constructor($$source: Partial<Artist> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sort_name" in $$source)) {
            this["sort_name"] = "";
        }
        if (!("normalization_key" in $$source)) {
            this["normalization_key"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artist instance from a string or object.
     */
    static createFrom($$source: any = {}): Artist {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artist($$parsedSource as Partial<Artist>);
    }
}

/**
 * Composer represents a music composer
 */
export class Composer {
    "id": string;
    "name": string;
    "normalization_key": string;

    /** Creates a new Composer instance. */
    constructor($$source: Partial<Composer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("normalization_key" in $$source)) {
            this["normalization_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Composer instance from a string or object.
     */
    static createFrom($$source: any = {}): Composer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Composer($$parsedSource as Partial<Composer>);
    }
}

/**
 * EQBand represents a single frequency band in the equalizer
 */
export class EQBand {
    "index": number;
    "frequency": number;

    /**
     * in dB, -12 to +12
     */
    "gain": number;

    /**
     * Q factor
     */
    "bandwidth": number;

    /** Creates a new EQBand instance. */
    constructor($$source: Partial<EQBand> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("frequency" in $$source)) {
            this["frequency"] = 0;
        }
        if (!("gain" in $$source)) {
            this["gain"] = 0;
        }
        if (!("bandwidth" in $$source)) {
            this["bandwidth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EQBand instance from a string or object.
     */
    static createFrom($$source: any = {}): EQBand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EQBand($$parsedSource as Partial<EQBand>);
    }
}

/**
 * EQProfile represents a named equalizer preset
 */
export class EQProfile {
    "id": string;
    "name": string;
    "is_active": boolean;
    "bands": EQBand[];

    /** Creates a new EQProfile instance. */
    constructor($$source: Partial<EQProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("bands" in $$source)) {
            this["bands"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EQProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): EQProfile {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bands" in $$parsedSource) {
            $$parsedSource["bands"] = $$createField3_0($$parsedSource["bands"]);
        }
        return new EQProfile($$parsedSource as Partial<EQProfile>);
    }
}

/**
 * Genre represents a music genre
 */
export class Genre {
    "id": string;
    "name": string;
    "normalization_key": string;

    /** Creates a new Genre instance. */
    constructor($$source: Partial<Genre> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("normalization_key" in $$source)) {
            this["normalization_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Genre instance from a string or object.
     */
    static createFrom($$source: any = {}): Genre {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Genre($$parsedSource as Partial<Genre>);
    }
}

/**
 * Lyric represents a music lyric
 */
export class Lyric {
    "track_id": string;
    "content": string;
    "source": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Lyric instance. */
    constructor($$source: Partial<Lyric> = {}) {
        if (!("track_id" in $$source)) {
            this["track_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Lyric instance from a string or object.
     */
    static createFrom($$source: any = {}): Lyric {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Lyric($$parsedSource as Partial<Lyric>);
    }
}

/**
 * MetadataUpdate holds user-editable fields for writing tags back to an audio file.
 */
export class MetadataUpdate {
    "Title": string;
    "Artist": string;
    "AlbumTitle": string;
    "Genre": string;
    "Composer": string;
    "Year": number;
    "TrackNumber": number;
    "TotalTracks": number;
    "DiscNumber": number;
    "TotalDiscs": number;

    /** Creates a new MetadataUpdate instance. */
    constructor($$source: Partial<MetadataUpdate> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Artist" in $$source)) {
            this["Artist"] = "";
        }
        if (!("AlbumTitle" in $$source)) {
            this["AlbumTitle"] = "";
        }
        if (!("Genre" in $$source)) {
            this["Genre"] = "";
        }
        if (!("Composer" in $$source)) {
            this["Composer"] = "";
        }
        if (!("Year" in $$source)) {
            this["Year"] = 0;
        }
        if (!("TrackNumber" in $$source)) {
            this["TrackNumber"] = 0;
        }
        if (!("TotalTracks" in $$source)) {
            this["TotalTracks"] = 0;
        }
        if (!("DiscNumber" in $$source)) {
            this["DiscNumber"] = 0;
        }
        if (!("TotalDiscs" in $$source)) {
            this["TotalDiscs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetadataUpdate($$parsedSource as Partial<MetadataUpdate>);
    }
}

/**
 * PlaybackState represents the current state of the audio player
 */
export enum PlaybackState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlaybackStatePlaying = "playing",
    PlaybackStatePaused = "paused",
    PlaybackStateStopped = "stopped",
};

/**
 * PlayerStatus represents the full state of the playback engine for the UI
 */
export class PlayerStatus {
    "track_id": string;
    "playback_state": PlaybackState;

    /**
     * Current position in seconds
     */
    "position": number;

    /**
     * Total duration in seconds
     */
    "duration": number;

    /**
     * 0.0 to 1.0
     */
    "volume": number;
    "muted": boolean;
    "repeat_mode": RepeatMode;
    "shuffle": boolean;

    /** Creates a new PlayerStatus instance. */
    constructor($$source: Partial<PlayerStatus> = {}) {
        if (!("track_id" in $$source)) {
            this["track_id"] = "";
        }
        if (!("playback_state" in $$source)) {
            this["playback_state"] = PlaybackState.$zero;
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("muted" in $$source)) {
            this["muted"] = false;
        }
        if (!("repeat_mode" in $$source)) {
            this["repeat_mode"] = RepeatMode.$zero;
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayerStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerStatus($$parsedSource as Partial<PlayerStatus>);
    }
}

/**
 * Playlist represents a music playlist
 */
export class Playlist {
    "id": string;
    "name": string;
    "description": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Playlist instance. */
    constructor($$source: Partial<Playlist> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     */
    static createFrom($$source: any = {}): Playlist {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Playlist($$parsedSource as Partial<Playlist>);
    }
}

/**
 * RepeatMode represents the repeat behavior of the player
 */
export enum RepeatMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RepeatModeOff = "off",
    RepeatModeOne = "one",
    RepeatModeAll = "all",
};

/**
 * SyncProgress represents the current progress of a library sync
 */
export class SyncProgress {
    "current": number;
    "total": number;
    "path": string;

    /** Creates a new SyncProgress instance. */
    constructor($$source: Partial<SyncProgress> = {}) {
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncProgress($$parsedSource as Partial<SyncProgress>);
    }
}

/**
 * ThemeColors holds extracted palette data from the current track's artwork
 */
export class ThemeColors {
    /**
     * hex e.g. "#E11D48" — highest saturation cluster
     */
    "vibrant": string;

    /**
     * hex — lowest saturation cluster
     */
    "muted": string;

    /**
     * hex — largest pixel-count cluster
     */
    "dominant": string;

    /** Creates a new ThemeColors instance. */
    constructor($$source: Partial<ThemeColors> = {}) {
        if (!("vibrant" in $$source)) {
            this["vibrant"] = "";
        }
        if (!("muted" in $$source)) {
            this["muted"] = "";
        }
        if (!("dominant" in $$source)) {
            this["dominant"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeColors instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeColors {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeColors($$parsedSource as Partial<ThemeColors>);
    }
}

/**
 * TrackDTO represents a track with its related entities populated for the frontend
 */
export class TrackDTO {
    "id": string;
    "path": string;
    "title": string;
    "sort_title": string;
    "album_id": string;
    "year": number;
    "track_number": number;
    "total_tracks": number;
    "disc_number": number;
    "total_discs": number;

    /**
     * in seconds
     */
    "duration": number;
    "bitrate": number;
    "sample_rate": number;
    "format": string;
    "artwork_key": string;
    "raw_artist_names": string;
    "raw_album_artist_names": string;
    "raw_genre_names": string;
    "raw_composer_names": string;
    "copyright": string;
    "other_metadata": string;
    "file_size": number;
    "is_favorite": boolean;
    "mtime": time$0.Time;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "artists"?: (Artist | null)[];
    "album"?: Album | null;
    "album_artists"?: (Artist | null)[];
    "genres"?: (Genre | null)[];
    "composers"?: (Composer | null)[];

    /** Creates a new TrackDTO instance. */
    constructor($$source: Partial<TrackDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sort_title" in $$source)) {
            this["sort_title"] = "";
        }
        if (!("album_id" in $$source)) {
            this["album_id"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("track_number" in $$source)) {
            this["track_number"] = 0;
        }
        if (!("total_tracks" in $$source)) {
            this["total_tracks"] = 0;
        }
        if (!("disc_number" in $$source)) {
            this["disc_number"] = 0;
        }
        if (!("total_discs" in $$source)) {
            this["total_discs"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("bitrate" in $$source)) {
            this["bitrate"] = 0;
        }
        if (!("sample_rate" in $$source)) {
            this["sample_rate"] = 0;
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("artwork_key" in $$source)) {
            this["artwork_key"] = "";
        }
        if (!("raw_artist_names" in $$source)) {
            this["raw_artist_names"] = "";
        }
        if (!("raw_album_artist_names" in $$source)) {
            this["raw_album_artist_names"] = "";
        }
        if (!("raw_genre_names" in $$source)) {
            this["raw_genre_names"] = "";
        }
        if (!("raw_composer_names" in $$source)) {
            this["raw_composer_names"] = "";
        }
        if (!("copyright" in $$source)) {
            this["copyright"] = "";
        }
        if (!("other_metadata" in $$source)) {
            this["other_metadata"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("is_favorite" in $$source)) {
            this["is_favorite"] = false;
        }
        if (!("mtime" in $$source)) {
            this["mtime"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackDTO {
        const $$createField26_0 = $$createType2;
        const $$createField27_0 = $$createType6;
        const $$createField28_0 = $$createType2;
        const $$createField29_0 = $$createType9;
        const $$createField30_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField26_0($$parsedSource["artists"]);
        }
        if ("album" in $$parsedSource) {
            $$parsedSource["album"] = $$createField27_0($$parsedSource["album"]);
        }
        if ("album_artists" in $$parsedSource) {
            $$parsedSource["album_artists"] = $$createField28_0($$parsedSource["album_artists"]);
        }
        if ("genres" in $$parsedSource) {
            $$parsedSource["genres"] = $$createField29_0($$parsedSource["genres"]);
        }
        if ("composers" in $$parsedSource) {
            $$parsedSource["composers"] = $$createField30_0($$parsedSource["composers"]);
        }
        return new TrackDTO($$parsedSource as Partial<TrackDTO>);
    }
}

/**
 * WatchedFolder represents a directory being watched for music files
 */
export class WatchedFolder {
    "id": string;
    "path": string;
    "created_at": time$0.Time;

    /** Creates a new WatchedFolder instance. */
    constructor($$source: Partial<WatchedFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchedFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchedFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchedFolder($$parsedSource as Partial<WatchedFolder>);
    }
}

// Private type creation functions
const $$createType0 = Artist.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = EQBand.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Album.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = Genre.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Composer.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
