CREATE TABLE IF NOT EXISTS mini_player_state (
    id INTEGER PRIMARY KEY NOT NULL DEFAULT 1,
    x INTEGER NOT NULL DEFAULT 0,
    y INTEGER NOT NULL DEFAULT 0,
    width INTEGER NOT NULL DEFAULT 300,
    height INTEGER NOT NULL DEFAULT 300,
    always_on_top INTEGER NOT NULL DEFAULT 0,
    has_position INTEGER NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (id = 1)
);
INSERT OR IGNORE INTO mini_player_state (id) VALUES (1);
